include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${PROJECT_NAME})
set(CPACK_PACKAGE_VENDOR "Continental Automotive Systems")

set(CPACK_PACKAGE_VERSION_MAJOR ${Gpsd2ecal_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${Gpsd2ecal_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${Gpsd2ecal_VERSION_PATCH})
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${PROJECT_NAME})
set(CPACK_PACKAGE_CONTACT "oana.dumitruc@continental-corporation.com")
set(CPACK_SOURCE_STRIP_FILES "")

if(UNIX)
  set(CPACK_GENERATOR "DEB")
  set(CPACK_SOURCE_GENERATOR "TGZ")
  set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/continental/gpsd2ecal")
  set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Oana Dumitruc <oana.dumitruc@continental-corporation.com>")
  set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
  set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS ON)
  set(CPACK_DEBIAN_PACKAGE_DEBUG ON)
  #set(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_BINARY_DIR}/../_setup")
  set(CPACK_OUTPUT_FILE_PREFIX _deploy)
endif()

set(CPACK_SOURCE_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")
set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README  ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

list(APPEND system_requirements 
		"ecal (>= 5.9.1)"
		"gpsd"
	        "gpsd-clients"
)

set(CPACK_DEBIAN_PACKAGE_DEPENDS "${system_requirements}")

get_cmake_property(CPACK_COMPONENTS_ALL COMPONENTS)
include(CPack)
